version: "3.2"
services:
  nginx_crud:
    container_name: nginx_crud
    image: nginx:1.17.8
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./code:/var/www
    links:
      - php_crud
  php_crud:
    container_name: php_crud
    image: php:7.4-fpm
    working_dir: /var/www
    volumes:
      - ./code:/var/www
